### ISSUE TITLE
site content audit: quick answers: compliance

### ISSUE THREAD

**Issue by leahbannon** [18F/fec-alpha#10]
medium

**Comment by kategarklavs** [comment]
@leahbannon Feel free to assign this issue to me and Emileigh (doesn't look like I can assign myself just yet)

**Comment by leahbannon** [comment]
cc @emileighoutlaw

**Comment by kategarklavs** [comment]
Having taken an initial look at the filing/compliance-related content, I'm going to say this is a large task — updating now.

cc @emileighoutlaw @leahbannon
