### ISSUE TITLE
initial wireframe drafts

### ISSUE THREAD

**Issue by leahbannon** [18F/fec-alpha#12]
medium

**Comment by jenniferthibault** [comment]
would be really helpful to follow progress on this. please loop me in when you're ready for review!

**Comment by noahmanger** [comment]
Here's the latest round. http://invis.io/WN37OI1PE

As I understand it, there's basically two potential purposes that this page serves in the near future:
1. Landing page: Serve as a landing page to communicate our beta progress;
2. Proto-Homepage: Serve as a beta version of the ultimate home page, testing functionality that we may want to live on the homepage eventually.

Some of these versions tilt more in one direction than the other. FWIW, I think it's best to go with a direction that's mostly #1, as that will be less controversial and easier to get up and running while we focus our energy on the filing functionality.
