### ISSUE TITLE
Test static prototypes with users

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-alpha#17]
Use InVision (or something else) to test the basic homepage wireframes with users.
- [ ] Find 3 outside users
- [ ] Find 2 FEC users
- [ ] Run tests
- [ ] Synthesize findings

**Comment by jenniferthibault** [comment]
@noahmanger do we want to bump homepage testing with new users up into this sprint?

**Comment by noahmanger** [comment]
Yep. We'll actually have a live page to test, too.

**Comment by noahmanger** [comment]
No longer relevant.
