### ISSUE TITLE
Design visual comps of beta (transition) landing page

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-alpha#18]
Use Jennifer's work on the styles to create visual designs for the new homepage.

**Comment by jenniferthibault** [comment]
First iterations in InVision here, to be reviewed in Design review 8/17 

https://invis.io/CM3TK9F8A

![beta home](https://cloud.githubusercontent.com/assets/11636908/9256742/457bfdf4-41bf-11e5-822c-1428467dffa0.png)
![beta home2](https://cloud.githubusercontent.com/assets/11636908/9256743/457d9df8-41bf-11e5-884a-2c3e0957ed43.png)

**Comment by LindsayYoung** [comment]
I love this! Great work!

**Comment by jenniferthibault** [comment]
Open question areas from 8/17 Design Review:
- how much preview/call to action do we want to offer? Is a simple update page with clear nav (as is) enough? or do we want to preview information from the existing sections? (Calendar, Data, Registration & Reporting) cc @noahmanger @onezerojeremy 
- what type of image feels right for leading this page? (Filing new issue now)

**Comment by jenniferthibault** [comment]
Working draft:

![beta home 2](https://cloud.githubusercontent.com/assets/11636908/9396438/23923bfa-4763-11e5-802b-95343af8e98f.png)

**Comment by jenniferthibault** [comment]
Most recent draft up for consideration:

![beta home 3](https://cloud.githubusercontent.com/assets/11636908/9523601/c1206596-4ca8-11e5-8933-32485c0658b0.png)
