### ISSUE TITLE
Draft "What is FEC?" content

### ISSUE THREAD

**Issue by leahbannon** [18F/fec-alpha#25]
**Goal:** Test a re-write of FEC's "About FEC" page.

**Criteria:** Necessary team members review and approve. FEC reviews.

**Steps:** 
- [x] Capture current "About FEC" content
- [x] Condense, rewrite, and otherwise edit as necessary

https://docs.google.com/document/d/1vNFtrgbMqXGOhXxbUXIEXBGS5sCV4sv2kyF96ETjvAM/edit

**Comment by emileighoutlaw** [comment]
Not urgent, but @leahbannon @rdpiazza this re-write is ready for your eyes.
