### ISSUE TITLE
Content assessment and recommendations

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-alpha#31]
**Goal:** Explain findings of content audit and make recommendations in a more user-friendly format than the audit's expansive spreadsheet.

Will consider the following:
- Audience
- Titling
- Information Accessibility
- Style
- Overlap
- Scope
- POV
- Tone

Will also provide sample content re-writes.

**Criteria:** Necessary team members review and approve. Share findings with FEC.

**Steps:** 
- [x] KG create document
- [x] KG and EB develop and solidify findings recommendations

**Comment by emileighoutlaw** [comment]
Link to document: https://docs.google.com/document/d/1ODLaql54DwXabIZKWzPfx6TKrD9yR9zosYeiJldWhJo/edit#

**Comment by noahmanger** [comment]
Oops, looks like I need access.

**Comment by emileighoutlaw** [comment]
You should have access now, @noahmanger!

**Comment by noahmanger** [comment]
Finally got around to reading this. This is terrific!

**Comment by jenniferthibault** [comment]
Sorry it took me a bit to review as well. BUT HOLY SMOKES! The suggested examples at the end are especially persuasive.

**Comment by emileighoutlaw** [comment]
Thanks, everyone! ^^ @kategarklavs

**Comment by kategarklavs** [comment]
Woooo(!) This is great to hear :)
