### ISSUE TITLE
Finalize mood board by gathering feedback from FEC team

### ISSUE THREAD

**Issue by leahbannon** [18F/fec-alpha#32]

**Comment by jenniferthibault** [comment]
Gather feedback on the visual identity design concepts in the first round of mood boards, and create a final board that captures the new visual identity components.
- [x] Put mood boards on InVision for review
- [x] Coordinate meeting w/ FEC team. Will need at least one DC staff member in the room with them. 
- [x] Prep talking points for each board & style & how they match content goals 
- [x] Small group workshop on mood board selection
- [x] Refine mood boards based on feedback from small group
- [x] Present refined mood boards to commissioners
- [x] Choose one mood board (or one main board with elements from others that we feel are more successful) to edit.
- [x] Use the selected board to create a system of visual elements that will be applied to the new home page design

@emileighoutlaw do you want to join me for this presentation? Or review my talking points & designs for how they sync up w/ content strategy if the meeting isn't the best use of time?

Future implications: OpenFEC visual design, print and environmental elements

**Comment by jenniferthibault** [comment]
Closing in favor of #51, #52, & #53, which break this down into smaller steps.
