### ISSUE TITLE
Create flows around committee on-boarding

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-alpha#33]
**Goals:** Create flow diagrams to illustrate the key steps for an interface to enhance the committee onboarding experience.

**Criteria:** 18F team reviews and gives the :+1: to the flows.

**Background:**
A major theme of the filing research is the fact that the "onboarding" process for new committees is challenging to people. We believe there may be ways that an improved interface around filing (including what you must do before and after you file your form 1) can help ease these pain points.

**Comment by onezerojeremy** [comment]
The following is a service blueprint draft of a possible filer on-boarding process that tweaks the existing one. 

http://mur.al/mjRd7kgx

![filer-onboarding](https://cloud.githubusercontent.com/assets/474916/8528157/47727eba-23df-11e5-9087-dd1aa9ea20fd.png)
