### ISSUE TITLE
Usability test new committee tools

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-alpha#41]
**Goal:** Conduct quick usabilty test on the new committee tool wireframes to validate basic concepts and functionality.

**Criteria:** 3-5 usability tests completed and analyzed.

**Steps:**
- [ ] Recruit and schedule participants
- [ ] Test 1
- [ ] Test 2
- [ ] Test 3
- [ ] Synthesize notes

**Dependencies:** #44 #43 #42 #40

**Comment by leahbannon** [comment]
Done.
