### ISSUE TITLE
Scope feasability of pre-check tool

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-alpha#45]
**Goal:** Determine if we want to pursue design and development of some sort of "reporting pre-check" tool that would help filers catch errors in their reports before they submit.

**Criteria:** Final :+1: / :-1: on the feature.

**Steps:**
- [ ] Discuss with dev team
- [ ] Check with FEC if necessary

**Comment by leahbannon** [comment]
Deciding to postpone this to September.
