### ISSUE TITLE
Design draft content node for knowledge base. 

### ISSUE THREAD

**Issue by onezerojeremy** [18F/fec-alpha#48]
Goal: create a sample piece of content for a knowledge base. We looked at some examples, including the candidate & committee guides, myUSCIS, gov.uk, and the CfA answers platform (in use in Oakland). 

Sample document here : https://docs.google.com/document/d/1DFSqpYgR6Khz2V6OcGCtghu_F-eEFYwyO2b-tzRwEwQ/edit#

![sample content layout draft](https://cloud.githubusercontent.com/assets/474916/8531074/de526148-23f2-11e5-802b-5721898898b2.png)

Cribbing from:
https://www.gov.uk/payroll-software/overview
https://my.uscis.gov/helpcenter/article/can-my-relative-wait-in-the-united-states-until-becoming-a-permanent-resident
http://answers.oaklandnet.com/quick_answers/do-i-need-a-permit-to-throw-a-party

**Comment by onezerojeremy** [comment]
cleaned up a bit and now in sketch with the other wires, on the drive at 
![screen shot 2015-07-09 at 11 04 04 am](https://cloud.githubusercontent.com/assets/474916/8598996/eb58f060-262b-11e5-99da-ab79a9aabba3.png)
https://drive.google.com/open?id=0B_FgIWl2WPMEVXZTVHVaSHhjY28

##Thoughts:
- "Knowledge Hub" in the breadcrumbs is obviously a working title. Also need to loop back on the IA and figure out if it lives within Registration and Reporting, or outside of it. 
- "Worth Noting" feels not quite right to me, but we can clean it up later.
- "Legal Resources" now contains links to FECA, as well as AOs and Enforcement Actions. This will obviously depend on how many of each will be linked to; we'll need to investigate the average number of links, as well as the edge cases before coming up with a solid design for that, but thought it probably made sense to keep this minimalist.

**Comment by noahmanger** [comment]
This looks great. That IA question is a question I've had for a long time. Does this sort of thing belong in it's own section? Alongside other "legal resources" like AOs and EAs? Or alongside reporting and registration tools? I think as we develop the content we'll hopefully figure some of this out.

One style question I have (ping @emileighoutlaw ) is whether titles phrased as questions is the best way to go. Personally, I like it. But I'm not sure what the best practice is here.

**Comment by jenniferthibault** [comment]
This is in InVision here: https://invis.io/EZ3VFRKBS and being reviewed on 8/17's design review

![knowledge center item](https://cloud.githubusercontent.com/assets/11636908/9266761/7527ddda-4213-11e5-9c7a-e8d1082040f6.png)
