### ISSUE TITLE
Build a web style guide 

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-alpha#53]
1. **Goal:** Create a document that will guide the visual design of new web components
2. **Completion Criteria:** When a PDF or static web page containing components has been created
3. **Tasks to completion:**
4. [x] Organize patterns from #52 into a guide format, which will be working alpha
5. Dependencies: #32, #51, #52 

The working alpha could be turned into a digital product

**Comment by jenniferthibault** [comment]
Still adapting, and a work in progress, but here are the elements I'm tracking so far:

![web-style-guide](https://cloud.githubusercontent.com/assets/11636908/9045097/03e3fe64-39ef-11e5-9024-163130fd86a7.png)

**Comment by noahmanger** [comment]
Not sure if you were already planning on this, but I just thought of another thing we should include in the style guide: mobile styles, especially for typography.

**Comment by jenniferthibault** [comment]
Yesssss... That might warrant a second issue. Now in #58

**Comment by wluoFEC** [comment]
Love the design!

**Comment by jenniferthibault** [comment]
Closing to move further discussion of details into https://github.com/18F/fec-style/issues
