### ISSUE TITLE
Recipients typo

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-alpha#66]
Fix "recipients" box on data site from `receiptiants` to `recipients`.

**Comment by noahmanger** [comment]
Can you remind me where you saw this?

**Comment by emileighoutlaw** [comment]
Shoot. Looking now.

**Comment by emileighoutlaw** [comment]
It's in the "Browse Disbursements" tab!! Almost gave me a heart attack looking for it. Remind me to take bigger screenshots in the future ;)

**Comment by jmcarp** [comment]
Looks like there are two of these typos on the disbursements page--one in the filters and one in the detail panel. Pro tip: it's easier to search the code than the site:

```
$ ag "receipient"
static/templates/disbursements.hbs
5:      <td>Receipient Name</td>

templates/partials/disbursements-filter.html
15:{{ text.field('recipient_name', 'Receipient Name') }}
```

**Comment by emileighoutlaw** [comment]
Thanks for the tip @jmcarp :)
