### ISSUE TITLE
Help prep FEC site for beta announcement

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-alpha#68]

**Comment by leahbannon** [comment]
Help Pat style announcement on FEC homepage

**Comment by jenniferthibault** [comment]
A couple different ideas based on how straightforward (or not) implementing them on the current home page would be:

### 1:

 Replace website improvement call to action with beta.FEC call to action. The design here makes this announcement a little more visually prominent.
- Pros: works with existing infrastructure
- Cons: only visible from home page
  ![option 1](https://cloud.githubusercontent.com/assets/11636908/10345068/f274212a-6cf4-11e5-9871-298a14599b5d.png)

### 2:

Removing the website improvement call to action entirely, and adding an announcement banner at the top of the site. This banner would be present on the site until the user clicked the X. I don't imagine it as fixed position, I think it would scroll away with the top of the page. This allows us to simplify the home page, and make the announcement easy to find on any page.
- Pros: visible from all pages, allows home page to be simplified
- Cons: new feature that would have to be built
  ![option 2](https://cloud.githubusercontent.com/assets/11636908/10345006/904795ae-6cf4-11e5-8017-802621ae5a6c.png)

@emileighoutlaw / @amykort thoughts on the text for the announcement? 
@patphongs thoughts on implementation?

**Comment by leahbannon** [comment]
I like the banner more visually, but we had trouble implementing a banner with ethnio, which I'm not sure we ever really figured out. 

Also, it should always be "betaFEC" or "beta.FEC.gov"

**Comment by patphongs** [comment]
@jenniferthibault: I like option 2 as well. Let me see if I can get something like that working. If not, we may have to fall back to option 1. I'll keep you posted.

**Comment by AmyKort** [comment]
For what it's worth, I like them both.

**Comment by emileighoutlaw** [comment]
I think we should go with betaFEC wherever possible.

How does everyone feel about saying "new" twice in the banner? If we wanted to eliminate one, I think the first would be the one to trim. `Try out betaFEC with new tools for viewing campaign finance data`

**Comment by AmyKort** [comment]
I like your edit, @emileighoutlaw

**Comment by jenniferthibault** [comment]
@patphongs and I have been chatting through implementing this, and it looks like the second option (with top banner) is running into issues with how the nav is built, so the page can't shift down. We have some new options for how to handle the home page and all other pages, and all of them are able to be implemented, it just becomes a question of how prominent we'd like to make the announcement.

### Home page option 1 (same as before)

![option 1](https://cloud.githubusercontent.com/assets/11636908/10544448/782656be-73f1-11e5-80f7-45e40204eeeb.png)

### Home page option 2 (corner)

![option 2 copy 3](https://cloud.githubusercontent.com/assets/11636908/10544456/7e5d73fa-73f1-11e5-8726-05e0de0e957c.png)

### All other pages option 1 (corner)

![option 2 copy](https://cloud.githubusercontent.com/assets/11636908/10544465/86f3d2de-73f1-11e5-8065-3fba9e3790ef.png)

### All other pages option 2 (skinny)

![option 2 copy 2](https://cloud.githubusercontent.com/assets/11636908/10544518/d0048e46-73f1-11e5-854d-538f4d3a0caf.png)

I think the main question for the "all other pages" option, is how prominent you want the notification to be. If very prominent, then I think Option 1 (in the corner) is the way to go. If less prominent, then option 2.
Thoughts @AmyKort ?

**Comment by jenniferthibault** [comment]
Hi folks—after a few days of thinking on this, I'd like to propose that we use the corner option for all pages. Having one design will be the most straightforward to implement, and the corner option is more easily visible than the skinny banner.

Before we give @patphongs the green light to finish coding these up, any thoughts, differences of preference, or anything else from anyone?

![option 2 copy 3](https://cloud.githubusercontent.com/assets/11636908/10544456/7e5d73fa-73f1-11e5-8726-05e0de0e957c.png)

![option 2 copy](https://cloud.githubusercontent.com/assets/11636908/10544465/86f3d2de-73f1-11e5-8065-3fba9e3790ef.png)

**Comment by AmyKort** [comment]
I think the corner banner is good. Generally, I think we were looking for something prominent. I like the idea of having the link in the same place on all of the pages. I think the corner banner is easy to find and it doesn't otherwise disrupt the page. It also looks great--but everything you design looks great.

**Comment by LindsayYoung** [comment]
I like the idea of starting out with a less noticeable banner for a few weeks, and then going to the bigger banner when we are a bit more battle tested.

**Comment by leahbannon** [comment]
This looks good to me --> just need to make sure it says "beta.FEC.gov" or "betaFEC" --> never "beta.FEC"

**Comment by patphongs** [comment]
The code is ready on our side is referencing "betaFEC". It's ready to deploy after beta is launched live to the public.

**Comment by jenniferthibault** [comment]
Awesome! Thanks @patphongs — let me know if it's helpful for me to take a look. Seems like this is ready to close otherwise.
