### ISSUE TITLE
run card sorting interviews

### ISSUE THREAD

**Issue by leahbannon** [18F/fec-alpha#7]

**Comment by leahbannon** [comment]
large
~5 people

**Comment by leahbannon** [comment]
@andrewmaier also working on this

**Comment by noahmanger** [comment]
Andrew and I synced up on this and decided that this should happen after the content inventory is complete so we can use the findings from that exercise as the cards for card sorting. We can then run that sort with people we're interviewing in the FEC as well as 5ish filer-type people outside.

This means that this card sort will be based specifically around the filing & compliance content, not the site as a whole, which we think is right for this stage and the work we're about to do.
